steps:
  # Construir la imagen de Docker para la aplicación clasificadora.
  # Se usa el mismo comando 'docker build -t app_clasificadora .'
  # En esta caso Cloud Build se le adiciona dos etiqueta a la imagen.
  # $COMMIT_SHA: Variable de entorno que indica el HASH identificador de la
  #   compilación. Sirve para identificar diferentes compilaciones y generar
  #   un registro historico de compilaciones.
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'app_clasificadora',
      '.'
    ]
  # Renombra la imagen docker "app_clasificadora" al repositorio en
  # artifac-registry, el cual contiene el repositorio "app-clasificador-dev"
  # y guarda la imagen "app_clasificador".
  # La estructura de un repositorio artifac-registry es:
  # ${region}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}[:$COMMIT_SHA]
  # ${region} = us-central1
  # ${PROJECT_ID} = Es una variable de entorno global de Cloud Build
  #   del proyecto actual que ejecuta la compilación.
  # ${REPOSITORY} = Folder repositorio creado en el artifact-registry.
  # ${IMAGE_NAME} = Nombre de la imagen a guardar.
  # $COMMIT_SHA = Variable de entorno que indica el HASH identificador de la
  #   compilación. Sirve para identificar diferentes compilaciones. 
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'image',
      'tag',
      'app_clasificadora',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/app-clasificador-prod/app_clasificadora:$COMMIT_SHA'
    ]
  # PUSH = Enviar/Publicar
  # El comando "Docker push" se utiliza para publicar una imagen de Docker
  # en un registro de contenedores.
  # Un registro de contenedores es un servidor que almacena imágenes de Docker
  # y las hace disponibles para su descarga e instalación.
  # Al publicar una imagen de Docker en un registro de contenedores, estás haciendo
  # que la imagen esté disponible para que las aplicaciones cloud descarguen la
  # imagen y la utilicen en sus propios entornos.
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/app-clasificador-prod/app_clasificadora:$COMMIT_SHA'
    ]
  # Se desplegará la API en Cloud run en la región "us-central1".
  # La imagen de la aplicación se obtiene de la imagen previamente publicada.
  # El parámetro "--allow-unauthenticated" indica que la aplicación podrá ser
  # accedida por cualquier usuario sin necesidad de autenticación.
  # Nota: "--allow-unauthenticated" es un riesgo de seguridad, y solo es
  # usado por motivos educativos.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'app-clasificadora-prod',
      '--image', 'us-central1-docker.pkg.dev/${PROJECT_ID}/app-clasificador-prod/app_clasificadora:$COMMIT_SHA',
      '--region', 'us-central1',
      '--memory', '2Gi',
      '--allow-unauthenticated'
    ]
  # Nota: Este comando no es necesario en el futuro, ya que al usar la imagen docker "latest" al generar
  # la instancia en Cloud Run automaticamente tomará la última publicada, pero garantiza que las imagenes
  # en caché se renueven inmediatamente por la nueva versión.
  # Adicionalmente, en caso de no existir el servicio en Cloud Run entonces lo genera automáticamente.