steps:
  # Se desplegará la API en Cloud run en la región "us-central1".
  # La imagen de la aplicación se obtiene de la imagen previamente publicada.
  # El parámetro "--allow-unauthenticated" indica que la aplicación podrá ser
  # accedida por cualquier usuario sin necesidad de autenticación.
  # Nota: "--allow-unauthenticated" es un riesgo de seguridad, y solo es
  # usado por motivos educativos.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'app-clasificadora-qa',
      '--image', 'us-central1-docker.pkg.dev/${PROJECT_ID}/app-clasificador-qa/app_clasificadora',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]